name: LoginFlutter
description: Login with Node and Sequelize with Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.


version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  liquid_swipe: ^1.3.1
  gradient_app_bar: ^0.1.3
  
  google_nav_bar: ^5.0.3
  line_icons: ^2.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.2
  http: ^0.12.0
  flutter_svg: ^0.20.0-nullsafety.3
  #flutter_svg: ^0.5.0
  shared_preferences: ^0.5.2
  jose: ^0.1.2

  flutter_pusher: ^1.0.2 

  google_maps_flutter: ^2.0.3
  #geolocator: ^7.0.3


  flutter_map: 0.10.1+1
  location: ^2.3.5
  motion_tab_bar: ^0.0.1
  table_calendar: ^2.1.0
  cupertino_icons: ^1.0.2

  #neumorphic: ^0.4.0
  #flutter_neumorphic: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/login.png
    - assets/icons/
    - assets/markers/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/video.svg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: calibre
       fonts:
         - asset: fonts/calibre.ttf
     - family: MaterialIcons
       fonts:
         - asset: fonts/MaterialIcons-Regular.ttf
     - family: Mont
       fonts:
         - asset: fonts/Mont-Heavy.otf
    # - family: Product Sans
       #fonts:
        # - asset: assets/font/Product_Sans_Bold.ttf
        # - asset: assets/font/Product_Sans_Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
